sudo: false
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - LARAVEL_VERSION=4.1.*
  - LARAVEL_VERSION=4.2.*

before_script:
  - composer require "laravel/support:${LARAVEL_VERSION}"

script: phpunit
