sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - LARAVEL_VERSION=5.0.*

before_script:
  - composer require "laravel/framework:${LARAVEL_VERSION}"
  - mysql -e 'create database laravel;'

script: phpunit
